### ISSUE TITLE
Question: How can I get a plugin I've written to show output on the web interface?

### ISSUE THREAD

**Issue by TJOak** [JustinAzoff/ninfo_web#2]
Apologies if this isn't the right place to ask (or if this is simply "too old"), but I cannot figure out how to do it on my own.

I've written a nInfo plugin using the plugin-template. The checkbox for it shows up if I click "Multiple" on the web interface, and it outputs for other plugins like cymruwhois and siteadvisor, but not my own. 
I feel it has something to do with the template_html.mako file, but I have been unsuccessful in figuring it out. I looked at the siteadvisor_template_html.mako to get an idea, but I do not know what is supposed to go inside the ${ } or how to set it, if need be.
I also looked at the __init__.py for the Google safebrowsing plugin, and while essentially copying the render_template function into my own plugin's __init__.py did make the plugin work on the command line, still nothing showed up on the web interface.

Can you offer any help?

**Comment by JustinAzoff** [comment]
Hi!  I mostly use the django app version of the ninfo website these days, but they work the same in this case.  We will get your plugin working!

You are correct that it has to do with the template_html.mako file.

you CAN override the rendering functions in the plugin, which is what the Google safebrowsing plugin does, but must plugins use a template.

If everything is working new plugins and their output will automatically show up in the web interface.

The variables available in the template is based on the dictionary that get_info returns.. so if your plugin was

```
def get_info(self, arg):
    return { "language": "python", "keywords": ["for", "while"]}
```

you can use an html template like

```
<h2>${language} Keywords</h2>
<ul>
%for k in keywords:
    <li>${k}</li>
%endfor
</ul>
```

To test things, try out the library from the command line.  You can import the library and run your plugin and then try rendering each output mode, and see what happens.

```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> from ninfo import Ninfo
>>> n=Ninfo()
>>> print n.get_info("geoip", "1.2.3.4")
{'city': None, 'region_code': None, 'area_code': 0, 'time_zone': None, 'dma_code': 0, 'metro_code': None, 'country_code3': 'AUS', 'country_name': 'Australia', 'postal_code': None, 'longitude': 133.0, 'country_code': 'AU', 'latitude': -27.0, 'continent': 'OC'}
>>> print n.get_info_text("geoip", "1.2.3.4")
AU - Australia None

>>> print n.get_info_html("geoip", "1.2.3.4")
<pre>AU - Australia None
</pre>
>>>
```

I bet your plugin or html template is raising an exception somewhere.  If it works from the command line, then it's probably just an issue with the html template.

One issue the web UI has is that it doesn't do a good job of displaying errors to you.. it shows you the amount of errors in RED, but I need to make it show them to you when you mouseover the red bar.

**Comment by TJOak** [comment]
Thanks! I've _partially_ figured it out. I had been using the string forms of numbers as the keys to my dictionary, and based on what I've seen, I'm guessing ${ } tries to evaluate whatever is inside of it. My bad! As a quick workaround, I changed the keys from starting at str(0) to now start at chr(65). Putting ${A} in the text template now makes it work properly on the command line without using my own render_template function.

My text template looks like this:
`${A}`

My html template now looks like this:

```
<pre>${A}
</pre>
```

From the command line, both n.get_info_text and n.get_info_html output as I expect and without any exceptions. But it still is not outputting on the web interface for whatever reason. Any ideas?

**Comment by JustinAzoff** [comment]
Ah yes.. I could see numbers not working right since you can't have variable identifiers that are numbers.

If you are storing sequential keys in the dictionary should just store a list..

instead of

```
{ "A": 1, "B": 2, "C": 3}
```

just return

```
{ "data": [1,2,3]}
```

Have you restarted the web interface since you fixed your plugin?  It only loads the code once at startup so if you have changed anything you need to restart it to pick up the updates.  It also sets the caching headers based on the plugin settings, so it is possible that your browser has cached the reply if you set a really long cache_timeout.

You can rule the browser out by hitting the api from the commandline with curl

```
curl http://localhost:8000/info/txt/nameofyourplugin/argument
curl http://localhost:8000/info/html/nameofyourplugin/argument
```

should output the same things that the library functions output.

**Comment by TJOak** [comment]
Figured it out!
Your curl suggestion reminded me I was running this on an Apache server which does not necessarily run with the same permissions as me. My plugin reads from a file. Said file only had read permissions for me; chmod +r fixed it.

I hadn't thought of using a list, though, before you mentioned it in your first response, and it seems a lot easier.

Thanks for all your help!
